version: '3'
services:
  postgres:
    image: 'postgres:11-alpine'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: marble
    volumes:
      - postgres-data:/var/lib/postgresql/database
  prisma:
    image: prismagraphql/prisma:1.23
    depends_on:
      - postgres
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5433
            database: marble
            schema: public
            user: postgres
            password: ${POSTGRES_PASSWORD}
            migrations: false
            ssl: false

volumes:
  postgres-data:
    driver: local
